// Generates CSS variables + a typed token map from tokens/tokens.json
// (which is exported from the Figma "unified AI design system" file).
// Run:  node scripts/build-tokens.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const light = [];
const dark = [];
const fixed = [];
const tsColor = [];

for (const [collName, coll] of Object.entries(tokens)) {
  const isGradient = collName === 'M3 Gradients';
  const prefix = isGradient ? '' : 'color-';
  for (const v of coll.variables) {
    const cssName = `--${prefix}${kebab(v.name)}`;
    if (coll.modes.length === 1) {
      // Single value (M3 Fixed) — same in both themes
      fixed.push(`  ${cssName}: ${v.values.Value};`);
    } else {
      light.push(`  ${cssName}: ${v.values.Light};`);
      dark.push(`  ${cssName}: ${v.values.Dark};`);
    }
    if (v.type === 'COLOR') tsColor.push(`  ${v.name}: 'var(${cssName})',`);
  }
}

const css = `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand.
   Source of truth: Figma "unified AI design system" → tokens/tokens.json */

:root,
[data-theme='light'] {
  --font-sans: 'Roboto', system-ui, -apple-system, sans-serif;
${light.join('\n')}

  /* fixed (theme-independent) */
${fixed.join('\n')}
}

[data-theme='dark'] {
${dark.join('\n')}
}
`;

// ---- M3 expressive type scale (Standard + Emphasized) ----
const roles = [
  ['display', 'large', 57, 64, -0.25, 400],
  ['display', 'medium', 45, 52, 0, 400],
  ['display', 'small', 36, 44, 0, 400],
  ['headline', 'large', 32, 40, 0, 400],
  ['headline', 'medium', 28, 36, 0, 400],
  ['headline', 'small', 24, 32, 0, 400],
  ['title', 'large', 22, 28, 0, 400],
  ['title', 'medium', 16, 24, 0.15, 500],
  ['title', 'small', 14, 20, 0.1, 500],
  ['body', 'large', 16, 24, 0.5, 400],
  ['body', 'medium', 14, 20, 0.25, 400],
  ['body', 'small', 12, 16, 0.4, 400],
  ['label', 'large', 14, 20, 0.1, 500],
  ['label', 'medium', 12, 16, 0.5, 500],
  ['label', 'small', 11, 16, 0.5, 500],
];
const typeRule = (name, size, lh, ls, weight) =>
  `.text-${name} {\n  font-family: var(--font-sans);\n  font-size: ${size}px;\n  line-height: ${lh}px;\n  letter-spacing: ${ls}px;\n  font-weight: ${weight};\n}`;
const typography =
  `/* GENERATED by scripts/build-tokens.mjs — M3 expressive type scale */\n\n` +
  roles
    .flatMap(([g, sz, size, lh, ls, w]) => [
      typeRule(`${g}-${sz}`, size, lh, ls, w),
      typeRule(`${g}-${sz}-emphasized`, size, lh, ls, w === 400 ? 500 : 700),
    ])
    .join('\n\n') + '\n';

const ts =
  `// GENERATED by scripts/build-tokens.mjs\n` +
  `// Ergonomic token references for inline styles / JS.\n` +
  `export const color = {\n${tsColor.join('\n')}\n} as const;\n\n` +
  `export type ColorToken = keyof typeof color;\n`;

mkdirSync(join(root, 'src/styles'), { recursive: true });
writeFileSync(join(root, 'src/styles/tokens.css'), css);
writeFileSync(join(root, 'src/styles/typography.css'), typography);
writeFileSync(join(root, 'src/tokens.ts'), ts);
console.log('Generated: src/styles/tokens.css, src/styles/typography.css, src/tokens.ts');
